module build_assets

import os
import strings

const static_dir = 'static'
const out_file = 'src/generated_assets.v'

fn main() {
	mut sb := strings.new_builder(0)
	sb.writeln('// Code generated by build_assets.v — DO NOT EDIT')
	sb.writeln('module main')
	sb.writeln('')

	// map of path -> bytes variable name
	sb.writeln('pub const embedded_files = {')
	for file in os.walk_ext(static_dir, '') {
		if os.is_dir(file) {
			continue
		}
		rel := file.replace('\\', '/').all_after(static_dir + '/')
		// safe var name
		varname := 'f_' + rel.replace('/', '_').replace('.', '_').replace('-', '_')
		sb.writeln('\t"${rel}": ${varname},')
	}
	sb.writeln('}')
	sb.writeln('')

	// embed each file into a byte[] constant using embed_file
	for file in os.walk_ext(static_dir, '') {
		if os.is_dir(file) {
			continue
		}
		rel := file.replace('\\', '/').all_after(static_dir + '/')
		varname := 'f_' + rel.replace('/', '_').replace('.', '_').replace('-', '_')
		sb.writeln('pub const ${varname} = \$embed_file("${file}").to_string()')
	}

	os.write_file(out_file, sb.str()) or { panic(err) }
	println('Generated ${out_file}')
}
