// Code generated by build_assets.v — DO NOT EDIT
module main

pub const embedded_files = {
	'common.css':            f_common_css
	'course.css':            f_course_css
	'figure_zoom.css':       f_figure_zoom_css
	'figure_zoom.js':        f_figure_zoom_js
	'index.css':             f_index_css
	'math_rendering.js':     f_math_rendering_js
	'subject.css':           f_subject_css
	'table_of_contents.css': f_table_of_contents_css
	'table_of_contents.js':  f_table_of_contents_js
	'subject_search.js':     f_subject_search_js
}

pub const f_common_css = $embed_file('static/common.css').to_string()
pub const f_course_css = $embed_file('static/course.css').to_string()
pub const f_figure_zoom_css = $embed_file('static/figure_zoom.css').to_string()
pub const f_figure_zoom_js = $embed_file('static/figure_zoom.js').to_string()
pub const f_index_css = $embed_file('static/index.css').to_string()
pub const f_math_rendering_js = $embed_file('static/math_rendering.js').to_string()
pub const f_subject_css = $embed_file('static/subject.css').to_string()
pub const f_table_of_contents_css = $embed_file('static/table_of_contents.css').to_string()
pub const f_table_of_contents_js = $embed_file('static/table_of_contents.js').to_string()
pub const f_subject_search_js = $embed_file('static/subject_search.js').to_string()
